### ISSUE TITLE
Congratulations, your code has made it to TDWTF

### ISSUE THREAD

**Issue by undertheironbridge** [blakehawkins/zdex#10]
Thanks to #8 , it seems.
See here : https://thedailywtf.com/articles/put-in-order

**Comment by blakehawkins** [comment]
I accept PRs! (But you should read #8 and understand the API and use cases, first)

**Comment by blakehawkins** [comment]
BTW I recommend [morton_encoding](https://crates.io/crates/morton_encoding) for the high-performance, naive implementation

**Comment by rlupton20** [comment]
TDWTF article here is really quite poor quality (when referenced against #8 ).
